### ISSUE TITLE
github backups

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#101]
Create backups for the entire CICE Consortium github space (not just this CICE repo).

@apcraig and @dabail10 are already working on this.   The plan is for NCAR to include it as part of its regular CESM github backup process.

**Comment by eclare108213** [comment]
The repos are now being backed up at NCAR.  We need to check that the data is available and usable, should we need it.  My understanding is that the "metadata" (wikis?) is not yet backed up.

**Comment by eclare108213** [comment]
@dabail10 @duvivier   Please, could you get an update on the status of the backups?  What is being backed up, how often, and how to we access them should the need arise.  Thx

**Comment by duvivier** [comment]
@eclare108213 @dabail10 and I checked today on this. 

The following CICE-Consortium master repositories and wikis are backed up:
CICE, Icepack, Test-Results

The backups are done 3x day at 6am, noon, and 6pm. At midnight the backups become daily and remain become monthly after a month. These are stored for 2 years at which point we only keep a backup for things up to 2 years old and anything older is scrubbed.

We are able to look at these through an internal CGD webpage. If the need arises (hopefully it never does!) we can just get the most recent backed up version and import it into github as a brand new repository. Mark last tested this about 2 months ago to verify that the process was working properly, though I just checked the internal website today and could see actively backed up files.

There is not *yet* any backup of metadata (PR, Issues, checkouts/checkins). Mark is working on this because we want metrics for CESM and these same sorts of metrics would be useful for the Consortium as well. As of now there isn't a set date for this to be completed.

I think we still have a bit of research/digging to do to figure out more about how the release tags etc. are stored. I will follow up.

@dabail10 , If you have more to add feel free.

**Comment by duvivier** [comment]
@eclare108213 
I'm keeping this on the front burner here. We had some issues with this being done correctly. We're at the point where metadata and branches are being saved. However, it looks like Tags aren't being saved yet, which I think is imperative since these are essentially the releases. Mark Moore is working on it this week and has made progress but it isn't complete yet.

**Comment by eclare108213** [comment]
Thanks for the update!  And for following up on it.  This service is much appreciated.

**Comment by duvivier** [comment]
I tested this today with Mark Moore and Alice Bertini. From the code backed up on the cgd server I tested restoring the repo to a dummy repo I created for Icepack. I was successfully able to restore the master branch, all additional branches, tags, and the wikis. I could look at the history of the master branch (merges, commits, etc.)  

I think this is all the really important info we need. We weren't able to restore, to my dummy repo, the issues and pull requests to the nicely formatted manner they are in on github. However, they were saved as well as the repository history and you can look through them if necessary and use the repo history to find an issue or PR. 

So I'm going to go ahead and close this. I think it'll all taken care of and has been tested for verification that the code is restorable and will build and run.

**Comment by eclare108213** [comment]
Thank you!
