### ISSUE TITLE
testing notifications

### ISSUE THREAD

**Issue by duvivier** [CICE-Consortium/CICE#104]
Testing how this works. Assigned to @duvivier. Need @eclare108213 's input.

**Comment by eclare108213** [comment]
Thanks Alice.  Since this issue is assigned to you, I hope you get the notification...

**Comment by eclare108213** [comment]
and this is another notification method:  @duvivier

**Comment by duvivier** [comment]
Yes, I got notifications for both. If you want to really test, you can set up another test. Assign it to Tony and then mention me in it. I am now "unwatching" the repo as well.

**Comment by eclare108213** [comment]
We determined that you'll still get notifications from a github repository even if you are not watching it, provided that you are assigned to the issue/conversation or @-referenced in it.  However, you do need to either check your github notifications or have them sent to an email address where you will see them.  In my case, I sometimes miss notifications from non-Consortium github repos even when I'm referenced because of my local mail settings.  Regarding the CICE 6.0.0.alpha email, you wouldn't have seen it unless you were 'watching' the repository (in your github settings) and looking at all of the notifications.  Sorry for the numerous test messages, but I'm going to do one more test before declaring this issue complete:  @CICE-Consortium/devteam 
Now perhaps you will all get this message even if you aren't watching!
