### ISSUE TITLE
DOI info

### ISSUE THREAD

**Issue by duvivier** [CICE-Consortium/CICE#110]
When we have a "general DOI" for the repo, we should add that information to the README.md as well as the documentation so that we can point users to that and ask them to please cite that when using this code.  

Current Info: 
https://zenodo.org/record/1205675#.Wru_HZPwbUI
https://zenodo.org/record/1205675#.Wru_SpPwbUI

We may also want to create a CICE-Consortium community to tag these releases and point folks to that.

**Comment by anders-dc** [comment]
Hi Alice, the general DOI for CICE should be [10.5281/zenodo.1205674](https://doi.org/10.5281/zenodo.1205674).

**Comment by duvivier** [comment]
@eclare108213 Do only you have access to the zenodo info for the Consortium? I'd be happy to set up the CICE-Consortium community, but I think you may have to since I don't have the login. That way we can associate all releases of both CICE and Icepack with this community.

**Comment by eclare108213** [comment]
I tried to create a cice-consortium community on zenodo, but it already exists.  Maybe you can edit that one, and we'll use it?  Otherwise we'll need to name it something else.  I used the icon below, and here's what I put under 'description':

The CICE Consortium is a group of stakeholders and primary developers of the Los Alamos sea ice model (CICE), formed to maintain the current CICE model for existing and new users, to incorporate and maintain new research and development, and to accelerate scientific sea ice model development and its transfer into operational use.

The CICE model is the result of an effort to develop a computationally efficient sea ice component for use in fully coupled, atmosphere-ice-ocean-land global circulation models. Its development and maintenance have been led and coordinated by the Department of Energy since the early 1990s. Over the past two decades, a broad community of climate and weather forecasting groups has adopted the code, and in many cases, enhanced it. As the Department of Energy continues to develop a next generation of climate models for energy, continued support of CICE is needed while the community continues to improve and use the model. Therefore, the CICE Consortium has formed as a vehicle for collaboration in sea ice model development.

https://github.com/CICE-Consortium

![ciceiconsquare](https://user-images.githubusercontent.com/8173983/38043851-661fe08a-3275-11e8-9fb0-2ca9c4a50dcc.png)

**Comment by duvivier** [comment]
Hum... I had originally created a CICE-Consortium community, but I deleted when I realized that we couldn't share "curating" privileges with different users. I figured whatever user the zenodo releases were going to be associated with should be the curator. I just searched the zenodo communities and it says there aren't any communities matching either "CICE-Consortium" or "CICE consortium". Maybe it's worth trying to create a community again? 

Did you create the zenodo DOI links, etc. through your personal username etc. for zenodo, or is there a ciceconsortium master username?

**Comment by eclare108213** [comment]
I don't think there's a ciceconsortium master user for zenodo.  If you can't resurrect the community you created before, we'll need to name it differently.  CICE_Consortium?  CICE.Consortium?  I don't think we should use a space because it'll be part of the url.

**Comment by duvivier** [comment]
I tried and I can't resurrect the community. 

So when you try to create a community it says that the name cice-consortium is taken? 
When I try to go to : https://zenodo.org/communities/cice-consortium/
It tells me the page is not found. I did not try again to create this community myself since I don't want to create it again if it has the same curator problems I listed before.

In contrast, I tried going to:
https://zenodo.org/communities/openedu/
And the community opens up. When I tried to create a similar community with the same name it told me this name was already taken. This is what I expect would happen if the name is taken, so I'm perplexed why the cice-consortium is not able to be created.

@anders-dc do you have any idea how the Zenodo community for the CICE-Consortium can be created again?

**Comment by anders-dc** [comment]
Sorry, I have never used Zenodo communities. I suggest getting in touch with [Zenodo support](https://zenodo.org/support). Maybe the old user isn't entirely deleted from their system?

**Comment by duvivier** [comment]
Will do, thanks!

**Comment by eclare108213** [comment]
When you contact them, you could either ask them to resurrect it (and you’ll be the curator), or ask them to delete it completely so that I can create it again (and I’ll be the curator).  Or they can resurrect it and give it to me.  I do wonder if/how we can share duties.

**Comment by duvivier** [comment]
I asked them if they could delete it entirely. I did mention that the reason we were doing all this is that we couldn't figure out how to share curator duty and that we'd determined there should be a master curator. Hopefully they have some useful advice.

**Comment by eclare108213** [comment]
The zenodo community is here, with links to releases and DOI info:
https://zenodo.org/communities/cice-consortium
Closing issue.
