### ISSUE TITLE
frz_onset not bit-for-bit with different decompositions

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#137]
In recent testing, the restart field frz_onset is not bit-for-bit with different decompositions in the decomp_suite.  This error occurs at 1 gridcell only and needs to be further debugged.  Some thoughts as to what might be causing this are missing non-initialization, gx3 forcing issues, or an issue on a halo.  But those are all speculation at this point.

**Comment by eclare108213** [comment]
I tried to run the decomp suite on pinto and it fails because the maximum number of tasks per node is 16, which makes taskpernode=16/20=0 in cice.batch.csh.  Not sure what to do about this kind of issue.

[eclare@pi-fe1 CICE.ech]$ cice.setup -m pinto --grid gx3 --test restart --pes 1x20x5x29x80 --set dsectrobin --testid e2
 
cice.setup:
ICE_SANDBOX  = /turquoise/usr/projects/climate/eclare/CICE.v6.0/github/CICE.ech
ICE_CASENAME = pinto_intel_restart_gx3_1x20x5x29x80_dsectrobin.e2
ICE_CASEDIR  = /turquoise/usr/projects/climate/eclare/CICE.v6.0/github/CICE.ech/pinto_intel_restart_gx3_1x20x5x29x80_dsectrobin.e2
ICE_MACHINE  = pinto
ICE_COMPILER = intel
ICE_PES      = 1x20
ICE_GRID     = gx3 (100x116) blocksize=5x29x80
adding namelist mods set_nml.gx3
adding namelist mods set_nml.dsectrobin
running parse_settings.sh
running parse_namelist.sh
running parse_namelist_from_settings.sh
running cice.run.setup.csh
cice.batch.csh cice.run
1 20 16 climateacme    (added line: echo ${ntasks} ${nthrds} ${maxtpn} ${acct})
Division by 0.
/turquoise/usr/projects/climate/eclare/CICE.v6.0/github/CICE.ech/pinto_intel_restart_gx3_1x20x5x29x80_dsectrobin.e2/casescripts/cice.run.setup.csh: ERROR cice.batch.csh aborted
cice.setup: ERROR, cice.run.setup.csh aborted

**Comment by eclare108213** [comment]
This is not obvious to me.  I'm getting 4 failures (commenting out the problematic 20-thread case):
>      FAIL pinto_intel_restart_gx3_8x2x8x10x20_droundrobin bfbcomp pinto_intel_restart_gx3_4x2x25x29x4_dslenderX2.e3 different-data
>      FAIL pinto_intel_restart_gx3_8x2x8x10x20_droundrobin_maskhalo bfbcomp pinto_intel_restart_gx3_4x2x25x29x4_dslenderX2.e3 different-data
>      FAIL pinto_intel_restart_gx3_1x4x25x29x16_droundrobin bfbcomp pinto_intel_restart_gx3_4x2x25x29x4_dslenderX2.e3 different-data
>      FAIL pinto_intel_restart_gx3_1x1x50x58x4_droundrobin_thread bfbcomp pinto_intel_restart_gx3_4x2x25x29x4_dslenderX2.e3 different-data
>      4 of 84 tests FAILED

I reran with debugging turned on (both with and without -g) and got the same results, so everything is initialized (somehow).  There could be multiple problems; the 8x10 block size will have some padded blocks, and the 1-processor runs are using a partially separate code base from the mpi runs.  In fact, I also tried this:

>      FAIL pinto_intel_restart_gx3_1x4x25x29x16_dslenderX2 bfbcomp pinto_intel_restart_gx3_4x2x25x29x4_dslenderX2.e7 different-data

which indicates that the difference is not associated with the block decomposition but rather with the serial vs mpi code, at least for this case.

@apcraig do you have the coordinates (i,j,iblk,mtask) of the failing grid point, for at least one of the runs?

**Comment by apcraig** [comment]
I will looking into the 1x20 issue.  We should be able to have 20 threads even if there are 16 cores.  I think this is just a logic issue in the scripts that needs fixing.  My recommendation on the 1x20 test is to do 1x16 or even 1x8.  The blocksize should still work fine for that case.  I agree that serial vs mpi could be playing a role, but it's does not seem to be confined to just that.  My guess is that it's something else.

I do not have the coordinate of the problem gridcell.  I would have to do some additional debugging to get that.

**Comment by eclare108213** [comment]
The grid point in global coordinates is i,j = 69,3.  To find the local coordinates including task and block number, we'll need to dig into the decomposition code...  set dbug=.true. in subroutine create_blocks (in cicecore/cicedynB/infrastructure/ice_blocks.F90) to identify which block this point is in.  I'm out of time -- this is an incremental step, at least.

**Comment by eclare108213** [comment]
This note is for myself, for future reference.
CICE has never gotten bit-for-bit identical diagnostics, unless the cpp flag for that is turned on (DITTO I think).  So comparing the diagnostic files is a red herring -- it looks like the runs differ from the first time step, in all variables.  The restart files do not. 
This is the relevant grid cell in the two decompositions:
 pinto_intel_restart_gx3_4x2x25x29x4_debug_dslenderX2.e6:
>   lat    lon   TLAT   TLON     i     j   block  task
> -77.0 -153.0  -77.1 -153.0    20     3     1     1

 pinto_intel_restart_gx3_8x2x8x10x20_debug_droundrobin.e6:
>   lat    lon   TLAT   TLON     i     j   block  task
> -77.0 -153.0  -77.1 -153.0     6     3     2     0

**Comment by eclare108213** [comment]
I found the problem but haven't had a chance to fix the code or test it.  In subroutine init_restart_read, we need to broadcast nyr when use_restart_time is true.   Having the wrong value of nyr means that new_year is not set correctly except for master_task, and that can cause the freeze and melt onset diagnostics to be reset incorrectly.  It might also be a good idea to broadcast month, mday, sec, although those might be done elsewhere.
