### ISSUE TITLE
gravit not defined in ice_dyn_shared?

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#159]
In ice_dyn_shared we have:

#ifndef coupled
         ! calculate tilt from geostrophic currents if needed
         strtltx(i,j) = -fm(i,j)*vocn(i,j)
         strtlty(i,j) =  fm(i,j)*uocn(i,j)
#else
         strtltx(i,j) = -gravit*umass(i,j)*ss_tltx(i,j)
         strtlty(i,j) = -gravit*umass(i,j)*ss_tlty(i,j)
#endif

I run CICE6 non-coupled so my code compiles and works fine. However, I have the impression it would not work in coupled mode because gravit is not defined. 

Do we need a 'call icepack_query_parameters'?

**Comment by eclare108213** [comment]
@apcraig, would you check this in the version of RASM that includes CICE v6, please?  Maybe you already fixed it.

**Comment by apcraig** [comment]
It looks like neither RASM nor CESM set the "coupled" cpp.  They both use the CESMCOUPLED cpp.  The coupled cpp is used in limited places in CICE5 and CICE6.  We should review that cpp and decide whether it should be removed, changed, or otherwise.  The cpp appears in 

cicecore/cicedynB/infrastructure/comm/serial/ice_communicate.F90
cicecore/cicedynB/dynamics/ice_dyn_shared.F90
cicecore/cicedynB/general/ice_init.F90
cicecore/drivers/cesm/*/*.F90

**Comment by dabail10** [comment]
Actually, we do define "coupled" in the CESM build and use both CESMCOUPLED and coupled. We do the following in ice_init.F90:

#ifdef CESMCOUPLED
#define coupled
#endif 

We need both for various pieces of code. I agree that we do need to add the parameter gravit for the coupled case. I will do this.

Dave

**Comment by dabail10** [comment]
This is addressed in PR #182.

**Comment by dabail10** [comment]
Resolved in PR #191.
