### ISSUE TITLE
configure rectangular "box" case for advection tests

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#172]
We need a rotating slotted cylinder to test the advection options (incremental remap, upwind).  This could also be used to test the boundary conditions, if the velocity field were (u,0) and the x boundaries were cyclical.

**Comment by phil-blain** [comment]
I'd be glad to help with that but I'm not sure exactly what has to be done?

**Comment by eclare108213** [comment]
It's described here:
Lipscomb, W. H., and T. D. Ringler, 2005: An incremental remapping transport scheme on a spherical geodesic grid. Mon. Wea. Rev., 133, 2335–2350.

**Comment by eclare108213** [comment]
You'll need to set up an initial condition with this configuration (a slotted cylinder) and then create forcing options suitable for a couple of different tests, making the cylinder move in a circle within the domain and also making it move off the (cyclic) domain and re-enter on the other side.  The second case is harder!

**Comment by phil-blain** [comment]
I read the test description in the paper above and read the discussion in PR #151, and I examined the relevant code. I think I understand what I have to do, but I'm not sure how I should implement it. I'm thinking of 2 options : 

1. Create a netcdf file to initialize the test (ex. `iced_boxadv_v1.nc`), with the desired ice concentration (slotted cylinder) and imposed (`uvel,vvel`), then use `runtype = initial, restart=true, ice_ic = iced_boxadv_v1.nc` . The downside I see is that this file would have to be added to the CICE_data directory, which is at a different location for everyone and thus I'm not sure how this could be automatized (the `ice_ic` variable in `set_nml.boxadv` would change depending on the machine/env).

2. Hard code the initialization values, as is done for the box2001 test. In this case I think I should use a new value for the namelist variable `atm_data_type`, since `box` is used specifically for the box2001 test for setting the initial concentration in `ice_init.F90/set_state_var`. It could also be a new namelist variable (`ice_data_type` ?), since in this test (box advection) we do not impose atmospheric forcing, so the name `atm_data_type` seems less suitable...   Also, if I hard code the initial values I would have to initialize the ice velocity. I was thinking of a `box_data` subroutine in `ice_dyn_shared.F90` that would be called by `init_evp` if the namelist variable `ice_data_type` is set to `box`....

@eclare108213, @dabail10, @JFLemieux73 I would like some advice. I'm still in the process of getting to know the code base so maybe other options that I did not think of would be preferable.

**Comment by eclare108213** [comment]
These are both good options.  We haven't used a file for setting up tests in that past, though, and we'd need both binary and netcdf versions of it, so I'd lean toward the second option.  Also, if it's in the code then we can change it easier, if we want to.  We can differentiate the data_type for the various box tests.  Here's a suggestion (others weigh in on this, please):

- box2001 - the test we have now
- boxslotcyl - slotted cyclinder with rotating forcing
- boxbndx - unslotted cylinder with zonal forcing, for testing boundary conditions
- boxbndy - unslotted cylinder with meridional forcing, for testing boundary conditions

Then we can use the scripts to compare boxbndx and boxbndy as a symmetry test.
I would expect the forcing to be implemented at atm, but if it's easier or makes sense to do it as ocn, we can.

BTW, the scripts insert the proper data location for the forcing and other data, for each user, based on our machine files.  You don't need to worry about that.

**Comment by phil-blain** [comment]
Thanks for the input, I will go with option 2. Although, I thought that to test only advection it would be easier to directly impose the ice velocity, whereas from what I understand of your comment you seem to talk about using either the wind/ocean as forcing ?

**Comment by eclare108213** [comment]
That is a good point, but I think it would be easier to implement (and less invasive to the code) if you applied wind/ocean forcing rather than ice velocity.
