### ISSUE TITLE
Serial interfaces

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/CICE#178]
We have a whole bunch of extraneous stuff in the serial interfaces for CICE. Also, why are these built at all for the MPI cases?

Dave

**Comment by eclare108213** [comment]
Are you talking about the code that's in the serial/ folder?  That should not be built for the MPI cases, and in fact I don't think it can be.  That code is set up so that there's a 1-to-1 correspondence of subroutines between serial/ and mpi/, so that the calls in the main code are the same.  That does mean there's a lot of extraneous stuff for the serial routines, but they're rarely used.  If we want to change them, then we'd need to think carefully about the design.
Or maybe you're talking about something different here?

**Comment by dabail10** [comment]
For some reason everything under serial is being built in some of the base_suite tests. Maybe we have a couple serial tests in there? I agree that we want it to match the MPI calls. Maybe using optional variables? This is not a big priority.

**Comment by eclare108213** [comment]
We _should_ have serial tests in the base_suite.  I agree, not a high priority.

**Comment by apcraig** [comment]
Every CICE test suite, base_suite, quick_suite, decomp_suite, and travis_suite has at least 1 serial test.  If the pe layout is 1x*, the serial code is used.  Is the question whether the serial code contains a bunch of unused interfaces?  That could be.  The serial code might cover MPI interfaces that we are not using, just for completeness and maybe because the code came from other sources.  I don't think we should necessarily remove that code.  

I agree with @eclare108213 that the serial code should not be building with the mpi code and would be very surprised if it is.  If anyone is seeing that, we should look into it!  Otherwise, are there any outstanding questions or issues that need to be addressed or can we close this?

**Comment by dabail10** [comment]
I believe that only the single processor cases are building with the serial library. It was all just warnings I was seeing with the NAG compiler. I believe we can just close this.
