### ISSUE TITLE
document case settings

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#210]
The second column in the case settings table (options, format) needs to be filled out for settings that aren't strings:
https://github.com/CICE-Consortium/CICE/blob/master/doc/source/user_guide/ug_case_settings.rst

**Comment by eclare108213** [comment]
See #207

**Comment by duvivier** [comment]
@eclare108213 
Do you want there to be examples in this table? Otherwise it would be something like "string" as the format for most of these options. However, if we want to show what an example cice.settings file looks like after running cice.setup maybe that would be more useful. What do you think?

**Comment by eclare108213** [comment]
I don't think we should be examples.  That might be confusing because of the other entries in which a particular string is required.  And the default files are full of examples!  In general, I think it's fine to leave it generic ('integer', 'string', etc) in the documentation unless there are specific choices, and then put those in the table.

**Comment by duvivier** [comment]
Completed with PR #225 and #227
