### ISSUE TITLE
question re test directory names

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#211]
What determines the order of the information in the test directory names?
For example, these 2 entries in a .ts suite file yield the following case and run directories:
>     restart        gx1     4x2        sklgx1,medium
>     restart        gx1     8x1        bgcgx1,medium
>     pinto_intel_restart_gx1_4x2_medium_sklgx1/
>     pinto_intel_restart_gx1_8x1_bgcgx1_medium/

**Comment by apcraig** [comment]
The order is specified in the cice.setup script.  In the current implementation, the options are sorted alphabetically and then applied in that order.  That also determines the naming convention for the test.  The reason to do this is because then "sklgx1,medium" and "medium,sklgx1" will be sure to produce the same testname (for regression comparisons) and for the results to be identical between "sklgx1,medium" and "medium,sklgx1".  This assumes that there are no conflicts in the options files.  For instance, if one option should overwrite defaults from another option.  In that case, we will not want to sort the options and will also have to rely on users to understand those issues.  I think there are benefits to automatically sorting the options as long as we are able to keep the options independent enough.  But we can certainly rethink this implementation.  It would be easy to change.

**Comment by eclare108213** [comment]
I don't think we need to change it as long as we understand what is going on (and so can answer questions when the inevitably come up) and there's a good reason for it. Thanks for the explanation.
