### ISSUE TITLE
cice.build "reuse executable" feature

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#283]
There is currently a hidden feature in cice.build that support binary reuse. It exists solely to speed up the test suite by reusing the binary as much as possible and avoiding redundant builds.  There is some discussion about whether we want to make this feature public.  If we do, then we need to extend the documentation further and probably provide an example. We might even want to modify the interface so it matches the keyword interfaces that is the current standard in cice.setup (ie. cice.build --exe /scratch/$user/ciceexe/cice.exe.vabcd).  The current implementation just takes an optional single argument without a keyword.

I'm not entirely convinced we want/need to publicize this feature, but am open to discussion.  @phil-blain proposed we advertise this feature in PR #282 which was subsequently closed and shifted to this issue.  I think this is a very powerful in the test suite and will be used even for user defined custom suites.  But there are a number of subtle issues in the use of this feature that worries me if we publicize it.   The user has to be aware that certain options (DEBUG, serial vs MPI, threading flags, and actual compiler) create inconsistencies in the executable from case to case and that reusing a binary for a case with different settings may work, but not test the setup associated with the case.  With the test suite, since all of this is automated, the scripts are fully in control.

Anyway, I think this is worth discussing.  Is there value (or risk) in making this feature public.

**Comment by duvivier** [comment]
I'm not sure we want to make this feature public. My feeling is it's a hidden tool for us in terms of the testing for PRs etc. to the repo. It's not a feature to use for science to make things faster for that. I think it should be something *ONLY* used in the test suite and nothing else. To that end, keeping it hidden except to developers makes sense. The question then is how to document it for developers since all our normal documentation is freely available. I'm not sure how to do that...

**Comment by apcraig** [comment]
The feature is automatically used in all test suites without any control by the user.  So we don't need to document it in the classic sense, like "how to turn it on or off".  We could offer a new argument that would turn it off, although I'm not sure that's so valuable.  I guess the documentation that might be useful would support maintenance and extension of the scripts implementation.  We don't want the feature to get lost or broken in any upgrades to the scripts/testing implementation.  Is that the kind of documentation that is needed?

**Comment by eclare108213** [comment]
My suggestion here is to NOT treat this as a publicly available capability that the general user might consider leveraging, since it is conflict-error-prone.  However I do think it should be minimally documented (for maintenance etc, as @apcraig says).  I suspect that putting a basic description of how it works somewhere in the documentation isn't publicizing it in a practical sense, because most users (probably) don't read the documentation except a quick glance through the flags that are available for cice.setup.  So let's not give it a flag, and in the documentation do warn that it must be used with care and therefore we are not supporting it for general use.  Sound reasonable?

**Comment by phil-blain** [comment]
This will be done as part of #322

**Comment by phil-blain** [comment]
This was taken care of in #354 and can be closed.
