### ISSUE TITLE
Numerical libraries as CICE dependencies

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#284]
Hello all,
JF and me are in the process of adding an implicit dynamics solver, as we discussed in the last meeting. For now it runs successfully in serial mode. Before investing time to make it parallel, I wanted to get the general feeling of the Consortium towards the use of external libraries. How open are we about adding external dependencies such as linear/non-linear solvers from eg. Trilinos, SUNDIALS ? How about just BLAS? This would significantly save us development time, but these packages are quite big... What is your opinion ? Of course this would only be required for the implicit solver...
@eclare108213 @apcraig @dabail10 @JFLemieux73

**Comment by eclare108213** [comment]
Groups are increasingly moving toward using more of these kinds of packages.  I don't see a problem with linking to them, as long as how to do it is well documented and we have alternative options for users who do not wish to use them (in this case, our standard explicit solvers).  We would not distribute those packages with our codes.  The question is whether there will be ongoing, significant effort needed to maintain the interfaces with the external packages.

**Comment by apcraig** [comment]
It always worries me to add new requirements to users to install external libraries in order to use the model.  This can be quite burdensome, especially if multiple compilers are used on a given machine, compiler versions are changing relatively quickly, CICE is used inside a bigger coupled model with it's own build system, or the underlying libraries are evolving quickly especially without clean backwards compatibility.  These external libraries can be quite powerful and I would not say we should exclude using them simply by policy.  But we should think carefully about what external libraries we are proposing to require, even optionally, and how that impacts usability and maintenance of CICE over the longer term.  I think it's reasonable to use external libraries if they provide value, they are well maintained and supported, and they are reasonable to build.  If they are optional, that is useful, although that would suggest a cpp would be needed to remove the code references at build time.  Again, that is not horrible as long as there is value.  

PIO is a good example of an external library that we all could/should be using and testing inside CICE6 right now.  But nobody (not even me) has made the effort to build it on any machine as an external library or worked on linking it in as an external library.  I think that example goes a long way to showing the type of barrier these external libs create to users.

**Comment by apcraig** [comment]
We have added a section to the Software Development Practice to summarize the policy regarding this issue.  https://github.com/CICE-Consortium/About-Us/wiki/Software-Development-Practices and decided we can close the issue at this point.
