### ISSUE TITLE
resource index in sidebars

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#327]
Please add the resource index to the sidebar in all of the repos.  It's important!

**Comment by duvivier** [comment]
@eclare108213 Do you mean you want the sidebar of the wiki in all repos to look like this: https://github.com/CICE-Consortium/About-Us/wiki? 

This formatting had not been continued into the CICE or Icepack wikis since I thought we were just testing it for now, but I'm happy to add it:
https://github.com/CICE-Consortium/CICE/wiki
https://github.com/CICE-Consortium/Icepack/wiki

Just wanted to double check.

**Comment by phil-blain** [comment]
I agree, having a link to the 'Resource Index' page in the wiki sidebar of the Icepack and CICE wikis make finding the page easier and quicker.

**Comment by eclare108213** [comment]
I thought that the CICE and Icepack versions were the new ones.  Let’s decide what we want in them and then make those two consistent, at least.  Maybe just add the resource index.  The other repos would be expected to be different, but we can be thoughtful about them also.
e

**Comment by duvivier** [comment]
@eclare108213 The default in the wiki is just to have the pages from the wiki in the side bar. To make other links outside this repo's wiki we'll have to add the custom side bar like @apcraig did for the About-Us repo.

I agree with @phil-blain that it would be nice to have the resource index on there. But I don't want to add other pages besides what is there because originally we wanted to minimize individual links (that can easily be forgotten during updates and then broken) between places since this is the point of the resource index.

I'll work on implementing these for Icepack and CICE, and I'm also going to see if we can get the font bigger for all the wiki sidebars.

**Comment by duvivier** [comment]
@eclare108213 @phil-blain @apcraig Please let me know what you think about the new custom side bars. I think as soon as people are happy we can close this issue.

https://github.com/CICE-Consortium/About-Us/wiki
https://github.com/CICE-Consortium/CICE/wiki
https://github.com/CICE-Consortium/Icepack/wiki

**Comment by phil-blain** [comment]
I think they look good.

**Comment by apcraig** [comment]
Look good.  Thanks!

**Comment by eclare108213** [comment]
This looks good to me - thank you -
