### ISSUE TITLE
standardize QC testing workflow, requirements, documentation

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#347]
Define and document a standard workflow for QC testing, including instructions for what to do when the configuration being modified is not part of the default setup.   There should be a control run without the modification with which to compare a second run using the modified code; both runs may need some manual changes.  For modifications that do cause major changes in model output, before and after plots of ice thickness should be made and posted to the relevant PR.

#331 might be used as a test case for defining this workflow.

Also related:  #166 #333

**Comment by phil-blain** [comment]
Also related: #345 to make the plots :) !

**Comment by mattdturner** [comment]
I thought, to some extent, that this was already done.  [Code Compliance Testing Procedure](https://cice-consortium-cice.readthedocs.io/en/master/user_guide/ug_testing.html#code-compliance-testing-procedure) has some of the software requirements for the QC test, and [End to End Testing Procedure](https://cice-consortium-cice.readthedocs.io/en/master/user_guide/ug_testing.html#end-to-end-testing-procedure) is an "end-to-end" testing procedure.  I can see that this might need to be expanded upon, though.

**Comment by eclare108213** [comment]
Yes, thanks.  Let's review what's already there and clarify as needed.

**Comment by eclare108213** [comment]
The plots I was thinking of are maps, and #345 is for time series.  We don't have scripts to make maps (yet).

**Comment by mattdturner** [comment]
The current QC script will plot a map of 2-stage test failures, if the 2-stage test does indeed fail (only if all necessary Python packages are available).  Here is an example:

![image](https://user-images.githubusercontent.com/8278916/63449757-5a93e300-c406-11e9-8a75-cd63f409a89a.png)

Note that this QC test was done with randomly perturbed data in order to force a failure.

Should I update the QC script to plot a map of the `base` and `test` ice thicknesses for cases where either the 2-stage test or skill test fail?  Or would it be better to just have a separate script to handle creating maps of data?

**Comment by mattdturner** [comment]
I just realized that the map has the x-axis flipped... I'll have to create a PR to fix that

**Comment by apcraig** [comment]
I believe this issue has been addressed and will close it.  The documentation has been update thru a number of PRs and I think things are working OK and documentation is consistent.  We recently added a few sentences to the qc documentation for further clarification.

> QC testing should be carried out using configurations (ie. namelist settings) that exercise the active code modifications.  Multiple configurations may need to be tested in some cases.  Developers can contact the Consortium for guidance or if there are questions.
