### ISSUE TITLE
xcrun problems with older Macos systems

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#422]
I ran into a problem on my older Mac desktop with the conda implementation.  This flag,

`CFLAGS_HOST = -isysroot$(shell xcrun --show-sdk-path)
`

is resolved as "-isysroot" without any argument which then causes the makedep build to fail.  My version of xcrun on my desktop is 31.  This works fine on my laptop with xcrun version 43.1.  I don't know if it's xcrun or the sdk install on my desktop.  This desktop is 2010 vintage and I tend not to update things unless I absolutely need to.  It is running OS 10.11.6 so that is relatively recent.

A bit of output from xcrun on my desktop is

```
/Users/tcraig/Desktop/cice-consortium/cice.condatest/case1>xcrun --show-sdk-path

/Users/tcraig/Desktop/cice-consortium/cice.condatest/case1>xcrun --show-sdk-version
10.11
/Users/tcraig/Desktop/cice-consortium/cice.condatest/case1>xcrun --show-sdk-platform-path
xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
xcrun: error: unable to lookup item 'PlatformPath' in SDK '/'

```

I don't understand all the details here.

As a test on my desktop, I commented out the $CFLAGS_HOST and then everything built and ran fine.  Would it be appropriate to remove the CFLAGS_HOST setting in the conda setup for Macs?  What role does the CFLAGS_HOST variable play in the port?

**Comment by phil-blain** [comment]
@apcraig the reason we need to use `CFLAGS_HOST` is that `makdep.c` has some `#include` directives for system headers, i.e. what is usually found under `/usr/lib`.

In macOS 10.14, Apple removed the system headers from `/usr/lib`, and now they are exclusively found under $(xcrun --show-sdk-path). (The reason for this was mainly to simplify building code for different versions of macOS on the same Mac as multiple SDKs for different OS versions can be installed simultaneously.)

Now the thing is that the `clang` compiler that is packaged by conda-forge doesn't know about this (contrary to the system `clang`), so we need to tell it where is its sysroot so that it can find the headers.

Now my laptop is also at 10.11.6 and `xcrun --version` is 31. Here is the output for the same commands you ran:
~~~
$  xcrun --show-sdk-path
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
$ xcrun --show-sdk-version
10.12
$ xcrun --show-sdk-platform-path
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
~~~

so I'm under 10.11 but I have the 10.12 SDK installed ; I suspect that's due to a different version of Xcode. (mine is 8.2.1, you can check with `system_profiler SPDeveloperToolsDataType`)

**Comment by phil-blain** [comment]
So a simple workaround would be to first put the output of `$(shell xcrun --show-sdk-path)` in a separate variable, then define `CFLAGS_HOST` to that variable if it's not empty, or else to `/` .

**Comment by apcraig** [comment]
system profiler doesn't help me much.  If I grep the full output for spd, it returns nothing.

It would be good to have a workaround.  If I understand, if xcrun returns something, that'll be useful.  If it doesn't, then it's likely to know where the include files are by default?  

I will create a workaround as proposed by @phil-blain.  I will create PRs for Icepack and CICE and test on my desktop and laptop which should allow me to test both cases.  If anyone has other thoughts, please jump in.  Thanks.

**Comment by apcraig** [comment]
#424 and CICE #308 have been merged.  This should now be addressed.  I will close this.
