### ISSUE TITLE
gdb usage with conda

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#457]
Explore using gdb with the conda install.

**Comment by phil-blain** [comment]
Some notes:

**On Linux**, the system-installed GDB should be able to debug CICE (provided CICE is compiled in debug mode, i.e. `./cice.setup ... -s debug` . If GDB is not installed it can be installed using the system package manager. Alternatively it can also be installed with conda :
```bash
conda install -c conda-forge gdb
```
maybe we can think of adding this package to the `environment.yml` file if we feel enough CICE users will want to install it this way.

**On macOS**, GDB is not pre-installed. The debugger of the LLVM project, LLDB, which comes with the Xcode command line tools, does not really support Fortran, so it's not a good alternative. GDB can be installed on macOS. At the moment, the easiest way to do that is using the [Homebrew](https://brew.sh) package manager. Homebrew is a system-wide package manager like apt and friends on Linux.
Since macOS is getting more and more restrictive, after installation the GDB executable needs to be codesigned to be able to control other processes. See: 
- https://sourceware.org/gdb/wiki/PermissionsDarwin
- https://sourceware.org/gdb/wiki/BuildingOnDarwin

Note that on my Mac (10.11), last November I could not get the Homebrew-installed GDB (8.3 at the time) to work, despite doing the codesigning procedure. I was however able to compile GDB myself from the [release tarball](https://ftp.gnu.org/gnu/gdb) (the newest versions are at the bottom) by doing the old
```bash
cd gdb-<version>
./configure  # default prefix is /usr/local/
# or, if you don't have admin rights on your machine:
# ./configure --prefix=$HOME
make all install 
```
and then signing the executable following the instructions linked above.

As an aside, I'm working in my personal time on getting a GDB build for macOS available in conda-forge:
https://github.com/conda-forge/gdb-feedstock/pull/23

**Comment by phil-blain** [comment]
I think we should close this one. There is nothing more to do in the CICE repo rergarding this topic, I would say. Feel free to re-open if you feel it's not the case.
