### ISSUE TITLE
scripts: add support for CICE preference file for options

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#464]
I thought of that today: when I create new cases, I *always* want to use `-s debug,buildincremental` but I often forget to set these options. 

It would be great if `cice.setup` could read a `~/.ciceinit` (or similar) file in user's home directory and automatically apply any options it finds there (optionally with a way to disable this behaviour on a case by case basis).

**Comment by apcraig** [comment]
I think this is an interesting idea, although I'm not sure how widely it would be used.  Can we clarify requirements.  What happens when running a test or test suite, do you want the "user defaults" to always be applied?  This could create problems for test suites because you're changing the test suite by adding the user defaults and you'd probably always want to turn off that option.  Should this just be for cases with a command line option to turn it off?

**Comment by phil-blain** [comment]
Good point. I think that applying it just for cases and tests, but not test suites, makes sense.

**Comment by apcraig** [comment]
Proposing the file be called ~/.cice_set and the command line option to turn it off be --ignore_user_set.  Will only apply ~/.cice_set for cases and tests, not suites.  Any feeback on proposed names or implementation?  Using "set" because the command line option for the settings/options is --set (or -s).

**Comment by apcraig** [comment]
Correction, proposed command line argument will be ignore-user-set (dashes instead of underscores).

**Comment by apcraig** [comment]
Added in #494.
