### ISSUE TITLE
Feature CICE on fortran-lang.org

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#469]
The Fortran programming language has a new home one the web, https://fortran-lang.org.

This website has a "Packages" page which lists software written in Fortran, with a ["Scientific Codes"](https://fortran-lang.org/packages/scientific) section in which I think CICE would nicely fit (WRF is in there, for example).

I'm just opening this issue to discuss if we want to make a PR there to feature CICE on this page.

@apcraig @eclare108213 @duvivier

**Comment by phil-blain** [comment]
Side note: I'd add a "Meta" (or similar) label for this one, and also maybe a "Community" label.

**Comment by duvivier** [comment]
Hum, I don't really have a strong feeling. We certainly fit their criteria. I guess what would be the benefit for us? Basically just visibility? I know a lot of industry (not just scientific groups) uses WRF, which is why it might be listed. Interesting that CESM is not linked. I'm not sure we need to be advertising to a large number of Fortran users who aren't in the CICE community. Also, maybe this is a silly comment, but Elizabeth isn't LANL re-coding everything to use for GPUs? Would CICE at some point not be in Fortran anymore?

**Comment by eclare108213** [comment]
I don't have a strong inclination either way on this one, either.  I certainly wouldn't mind.  My one hesitation is that the fortran in CICE is a mix of very old and somewhat newer, certainly not the latest and greatest, so calling this code out on a Fortan-centric page might invite criticism, or perhaps more "help" than we want!  But I'm open.

LANL is recoding climate model components for GPUs, but that's unlikely to find its way into CICE - more likely MPAS-seaice and DEMSI.

**Comment by apcraig** [comment]
I don't feel strongly about this either.  I had a look around the fortran-lang.org page and don't understand why it exists.  It might be nice if they had an About Us page or a project statement or something.  Maybe it's just a community resource that is trying to become a hub for interactions and development?  I don't see how adding CICE to the site provides much benefit or visibility to our community, but am open about the idea.
