### ISSUE TITLE
capture timing results

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#49]
Record timing results as part of the testing procedure, or at least flag them if changes are substantial in comparison tests.  Preferably include at least these:
Timer   2:  TimeLoop
Timer   3:  Dynamics
Timer   5:    Column

**Comment by mattdturner** [comment]
In order to post the timings to CDash, we can only have 1 timer logged.  We can include the timer information for multiple timers elsewhere (although I'm not sure where).

For example, http://my.cdash.org/viewTest.php?onlypassed&buildid=1338795 is what I have been working on today.  I've been putting the 'Timer 1: Total' timer into the Time field for the *_run tests for smoke tests only.  I could easily change to another timer, but we still have the issue of only a single timing being able to be posted to CDash.

**Comment by eclare108213** [comment]
If we can only choose one, then the best one is TimeLoop.  If that one is very different between runs, then we can look more closely at Dynamics, Column, etc. manually.

**Comment by mattdturner** [comment]
I think this was addressed in #125 .  The wiki is now showing timings for tests (https://github.com/CICE-Consortium/Test-Results/wiki/3eed537e29.conrad.intel.180418.000150).

**Comment by eclare108213** [comment]
Cool, thank you.
