### ISSUE TITLE
Improve doc for running on personal computers

### ISSUE THREAD

**Issue by phil-blain** [CICE-Consortium/CICE#529]
This is prompted by [this recent question](https://bb.cgd.ucar.edu/cesm/threads/problem-running-icepack-on-mac-icc-command.5701/) on the forum. 

I think we could make a few minor changes in the doc to make it more beginner-friendly:
1. We could rename the section "Porting to Laptop or Personal Computers" to "Running on Laptop or Personal Computers" to make it clearer
2. We should add a link to this section in the "Quickstart" section
3. We could even move the "Running on Laptop or Personal Computers" before the "Porting" section.

Thoughts everyone ?

@CICE-Consortium/devteam 

Note: this applies to both the CICE and Icepack documentation.

**Comment by eclare108213** [comment]
I agree it's a good idea to include a link for the conda instructions to the quickstart.  I'm ambivalent about "porting" versus "running", since running might also include the need to port but doesn't have to.

**Comment by apcraig** [comment]
I would keep the "Laptop or Personal Computer" more in Porting rather than Running.   Ultimately, how you run is no different on Laptops or HPC platforms.  But the porting is a little different.  Although with laptops/PCs, you can still have some traditional porting issues.

I could see pulling out the two Porting Sections under "Running CICE" and creating a section called "Porting CICE".  I guess I might suggest we put that before Running CICE.  But that may involve some refactoring of other sections like Software Requirements, but that's less clear.  In some ways, I think it works well enough organized as it is.

I think it's a good idea to add a link in the Quickstart section.

**Comment by apcraig** [comment]
I updated the quickstart guide in #532.  I will close this for now, but if anyone things there is more to do, please reopen.
