### ISSUE TITLE
Remove/fix close_boundaries and update box2001 and boxslotcyc tests

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#541]
The close_boundaries option does not work.  This option needs to be fixed or removed.  Currently, box2001 and boxslotcyc use close_boundaries and turning that option off changes answers, so it will continue to live in the code until some decisions are taken.  See also #540.

**Comment by TillRasmussen** [comment]
I am currently looking at the "freya_gnu_restart_gbox80_1x1_box2001" as a test case for the 1d solver as it is the only gbox case that is not bit for bit within the 1d and 2d comparison.

Can you elaborate a little on what does not work when the "close_boundaries option is chosen?
All it does is to add 2 rows/columns of land.

**Comment by apcraig** [comment]
@eclare108213 should clarify, but I believe closed boundaries do NOT work properly and should never have been set.  This is on our list of tests to review and fix.  It may involve setting the mask to land on the edges, but I'm not totally clear on that.

**Comment by eclare108213** [comment]
Unfortunately I don't remember the details, only the agony of trying to fix the problems and failing.  I can go in to my office at some point and find my notes.  It's possible that imposed land boundaries obviate the issues, so that whether the boundaries are set as open or closed doesn't matter, but if changing from one to the other is not BFB in @apcraig 's tests then there's still a problem.  The thing I couldn't get to work was the halo cells in the corners of the grid -- I couldn't make them work consistently.  What I'm not sure of is whether the answers would change when the grid was rotated (e.g. replace x with y etc), or if I was running into some other issue.

**Comment by TillRasmussen** [comment]
Ok, I will ignore that it fails then.

**Comment by apcraig** [comment]
I have been looking at this issue/PR.  I think we can close it.

What the box2001 and boxslotcyl do is set open boundaries, but then use the namelist flag close_boundaries=.true.  What that does is set a layer of two gridcells of land on the boundary.  This should be fine.  The thing that doesn't work is setting ew/ns_boundary_type to 'closed'.  If a user sets the boundary_type to 'closed', the model now aborts.  So I think this issue was created in error by me due to some confusion.

Does anyone disagree?  If nobody says anything, I'll close this in the next couple days.  In summary

- ew/ns_boundary_type = 'closed' does not work and aborts in CICE now.
- close_boundaries = .true. creates a 2 gridcell wide land mask in the grid at initialization.
- box2001 and boxslotcyl use close_boundaries=.true. to create a land mask on the boundary.
- turning off close_boundaries in the box2001 and boxslotcyl should change answers, so that is fine.

**Comment by eclare108213** [comment]
That makes sense, and yes it is confusing.  Could you check the docs to see whether this sufficiently explained there?  Maybe an update there is all that is needed.  (Or maybe we just need to be reminded to look at the documentation...)
