### ISSUE TITLE
conda MacOSX issues and Github actions

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#547]
Recently, we ran into some problems with conda on Mac OSX.  This is probably related to a change in the conda compiler distribution.  In the end, we needed to add -lgcc_eh to get CICE to compile with OpenMP but without MPI (i.e. -p 1x2).

A Forum topic was added to provide some guidance to the community, https://bb.cgd.ucar.edu/cesm/threads/conda-port-issues.5795/

Should we do anything about this in our documentation or implementation.

As an aside, @phil-blain used Github Actions to test the setup and verified the same issue as seen on an actual Mac OSX system.  Should we be leveraging Github Actions or a similar cloud/container tool to test additional platforms and/or versions of systems/compilers/etc?

https://github.com/phil-blain/CICE-conda/runs/1573686932

**Comment by phil-blain** [comment]
Just want to add for @JFLemieux73 who might me reading that I'm working on that in my own time (not for work). CICE is open-source after all :)

**Comment by phil-blain** [comment]
I just opened an issue in the conda-forge repo where the conda-forge gfortran is built:
https://github.com/conda-forge/gfortran_impl_osx-64-feedstock/issues/36

I managed to isolate the problem to the "threadprivate" directive used in the 1D EVP implementation.

**Comment by phil-blain** [comment]
This has been fixed in conda-forge. Recreating the "cice" env should install the new build of gfortran from conda-forge and this should not require `-lgcc_eh` at link time. See for example this successful run: https://github.com/phil-blain/conda-forge-macos-gfortran-openmp-bug/runs/1591889588?check_suite_focus=true

**Comment by apcraig** [comment]
I can confirm that conda works for me again.  Big thanks @phil-blain for leading the effort to resolve the problem!

Do we want to discuss using github actions (or similar) to supplement testing?  Or should this be closed for now.

**Comment by phil-blain** [comment]
I think it could be a good idea, eventually.

**Comment by eclare108213** [comment]
I started from the instructions [here](https://cice-consortium-cice.readthedocs.io/en/master/user_guide/ug_running.html#laptops) and didn't get very far:

> bash-3.2$ which conda
> bash-3.2$ curl -l https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86-64.sh -o ~/Downloads/miniconda.sh
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   379  100   379    0     0    796      0 --:--:-- --:--:-- --:--:--   794
> bash-3.2$ bash ~/Downloads/miniconda.sh
> /Users/eclare/Downloads/miniconda.sh: line 1: syntax error near unexpected token `newline'
> 

macOS Catalina version 10.15.7

**Comment by phil-blain** [comment]
Yeah, should be `x86_64` and not `x86-64` (underscore instead of dash). The doc is OK.

Regarding the permission problem, that looks like a new security feature in Catalina: https://support.apple.com/en-ie/guide/mac-help/mchld5a35146/10.15/mac/10.15. In that light I agree we should change the command so that the installer is dowloaded directly to $HOME to work around that problem.


~~~diff
# Download the Miniconda installer to ~/Downloads/miniconda.sh
- curl -L https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o ~/Downloads/miniconda.sh
+ curl -L https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o ~/miniconda.sh
# Install Miniconda
- bash ~/Downloads/miniconda.sh
+ bash ~/miniconda.sh
~~~
