### ISSUE TITLE
Implement the plastic potential of Ringeisen et al. 2021

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#636]
It is very simple to implement the plastic potential of Ringeisen et al. 2021 (a few lines of code). The rheology includes two ellipses (one for the yield curve and one for the flow rule...defined by the plastic potential). In Ringeisen et al, the yield curve is F=0 and the plastic potential is G=0. The ellipse aspect ratios are respectively eF and eG. When eF=eG the rheology is the standard Hibler 1979 rheology. Note that e_ratio will disappear.  Any idea for the names in the code?

1) eF, eG
2) eF_ratio, eG_ratio
3) e_yield_curve, e_plast_potential
other ideas?

**Comment by eclare108213** [comment]
I prefer such names to have enough information in them to guess what they are, without being so long that multiple lines of code are required whenever they are used.  F and G are not particularly enlightening in this context.  e is itself problematic, but it has been around so long, it's probably recognizable enough to keep.  Both F and G options are referring to aspect ratios, so that terminology is not very helpful in differentiating them.  And this all leads me to choose item 3 here, though I might suggest `e_yieldcurve` and `e_plasticpotential` to not have so many underscores.
Or `e_yieldcurve` and `e_plasticpot` to have them the same length for "pretty" code.

**Comment by phil-blain** [comment]
I think I agree with Elizabeth on this one. `e_yieldcurve` and `e_plasticpot` seem like a good compromise between clarity and brevity.

**Comment by eclare108213** [comment]
Can this issue be closed?  #649

**Comment by phil-blain** [comment]
I'd say yes, the PR is merged.
