### ISSUE TITLE
C-CD TEST: gx3

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#686]

**Comment by TillRasmussen** [comment]
![allmarch](https://user-images.githubusercontent.com/33480590/154689175-4c0fb9e9-43ea-44d8-8bb8-4e1518edf3c7.png)
![allsep](https://user-images.githubusercontent.com/33480590/154689239-a77f133b-8a9e-4b34-a1c5-cc7ebcb4144e.png)
Plots of ice thickness. March and september 2008. Run starts 1/1/2005

**Comment by eclare108213** [comment]
Thanks @TillRasmussen !  Please, would you also post difference plots, C-B and CD-B?  I would expect the largest differences to be in areas of convergence (or at least multi-year ice), since the errors will "pile up" there along with the sea ice volume.  So it's probably difficult to say whether these are strictly due to the shifted location of grid quantities, interactions at land boundaries, etc, but this is a good 'reality check' for guiding more idealized testing.

**Comment by TillRasmussen** [comment]
Here they are. An interesting thing is that it seems as if B and C are more similar in Antarctic
![diffmarch](https://user-images.githubusercontent.com/33480590/154693044-a635aa89-7194-468b-affe-9886f147dd29.png)
![diffsep](https://user-images.githubusercontent.com/33480590/154693103-abb6bf37-0509-4dbb-a605-5e17f7b8eb3f.png)
Again for March first, then september

**Comment by JFLemieux73** [comment]
FYI. Martin Losch has a paper where they compared B and C grid solutions. Look at figure 4b for example. As opposed to our results it looks like the ice is thicker in their B grid solution compared to the C solution. 

https://www.sciencedirect.com/science/article/pii/S1463500309002418?casa_token=2XpDdkbCg8UAAAAA:4CSOP_CmxfzPras7T0I1TC0Isvw-9iM1Gh9oBt_m5OKp_xSKyXL_htds3RDwruXr8aE207_D-Jb3

**Comment by dabail10** [comment]
This is a great resource. I believe that he did the staggering such that the velocities are at the W and S faces. Not sure what his grid looks like, but I wonder if this could explain why the B grid is thicker in his case?

**Comment by apcraig** [comment]
I think we should close this.  Anyone disagree?

**Comment by apcraig** [comment]
Closing, active discussions of C-grid testing in #792.  Feel free to reopen is needed.
