### ISSUE TITLE
cice.t-test.py script

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/CICE#710]
Hi all,

This was written for the QC testing in 2017 by @mattdturner. I know Matt is no longer actively involved here. I have found out that Basemap is not really supported anymore in python and there is a move to CartoPy. I am willing to update this, but I wanted to make sure someone else has not done this already.

**Comment by apcraig** [comment]
I don't think anyone else has made updates recently.  Thanks @dabail10.

**Comment by dabail10** [comment]
Turns out just had to do a pip install basemap to get it working. I will still work on updating to CartoPy.

**Comment by phil-blain** [comment]
I think Python is the perfect language for this kind of thing, I would definitely vote for keeping this script in Python, and work towards moving to Cartopy instead of basemap.

@dabail10 You could have used the conda environment (https://cice-consortium-cice.readthedocs.io/en/master/user_guide/ug_running.html#using-the-conda-configuration), this would have installed all needed packages for the plotting scripts :)

**Comment by dabail10** [comment]
@darincomeau noticed that this script reads in the T-test criteria from a file. I'm curious to know if there was a particular reason that @mattdturner did it this way? Ideally, we could be using some internal python libraries.

**Comment by dabail10** [comment]
Did we already redo this in cartopy? @daveh150 @phil-blain

**Comment by daveh150** [comment]
This script was updated to use cartopy in #742. 

The cice.t-test.py script still uses the lookup table files. There is a stats module within scipy, but I have not used it. I need to learn more to see if it could replace using look-up files.

I suggest we close this issue since it is vague, and open a separate issue to investigate using scipy test instead of lookup files.

**Comment by daveh150** [comment]
Since update to Cartopy was accomplished in #742, and the title of this issue is very general, I am closing this issue. I will open a separate issue to investigate alternatives to look-up tables for the T-Test.
