### ISSUE TITLE
C grid documentation

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#711]
The current cgridDEV documentation can be found here,

  https://apcraig-cice.readthedocs.io/en/cgriddev/

This issue will provide a space where we can make and aggregate comments as we finalize the documentation.

**Comment by dabail10** [comment]
This is great. Some thoughts:

1. As  u and v are collocated on the B-grid ... This should maybe be When u and v are collocated?

2. It looks like not much is changed in the dynamics section (2.5)? I guess most of this comes in in 3.1.

3. There is an extra period here, but it might be worth saying "normal" velocity components for C and tangential velocity components for D are solved.

"The ability to solve on the C and CD grids was added later. With the C grid, the u velocity points are located on the E edges and the v velocity points are located on the N edges of the T cell rather than at the T cell corners. On the CD grid, the u and v velocity points are located on both the N and E edges. To support this capability, N and E grids were added to the existing T and U grids, and the N and E grids are defined at the northern and eastern edge of the T cell. This is shown in Figure Schematic of CICE CD-grid.."

4. In section 3.1.2.5 in the discussion of the masks I don't think there should be an underscore in ice_tmask and ice_umask. We should also add icenmask and iceemask here.

So I am happy to work on this. I just wanted to note things here. Should we do this before the merge to main?

**Comment by eclare108213** [comment]
A few other things I noticed:

- references at the end of section 2.5.1 (before 2.5.1.1) aren't formatted and linked correctly.
- C-grid is mentioned in section 3.1.2 -- this needs to be updated, maybe just by removing the sentence "EVP is available on the C-grid through the MITgcm code distribution, http://mitgcm.org/viewvc/MITgcm/MITgcm/pkg/seaice/."
-  The organization of section 2.5 is a little wacky.  It was originally organized into 2 main sections, one for the momentum equation and one for the internal stress, since it's such a major physics component of the dynamics.  The wind stress term is treated elsewhere, and I'd just stuck the ocean stress term under the momentum equation header, since it was small.  I think the seabed stress section also needs to be under the momentum section, rather than in its own section.  Alternatively, we could create 3 major sections:  momentum time stepping, momentum surface stress terms (do you characterize seabed stress that way?), and rheology.  Other thoughts welcome.  I'd rather not refactor this by VP, EVP etc.

**Comment by apcraig** [comment]
Closing.
