### ISSUE TITLE
Reformulate incremental remapping on C-grid.

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/CICE#720]

**Comment by JFLemieux73** [comment]
I was in a meeting this morning with SI3 developers (Clément Rousset, Martin Vancoppenolle and Ed Blockey). They reiterated their interest in a remapping on C-grid. They think people from CICE and SI3 should collaborate on this for the development and testing. It would be nice to develop something modular enough so that it could be used easily in both models. I will set up a meeting between the two groups.  

FYI @eclare108213 ...

**Comment by dabail10** [comment]
I think we can close this as @JFLemieux73 has a nice solution as is.
