### ISSUE TITLE
check whether ice strength is calculated at the correct location.  Move to after last subcycle?

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#739]

**Comment by TillRasmussen** [comment]
I assume that this refers to the call to subroutine deformation when ksub == ndte?

If yes then the deformation call is used to calculate shear, divu, rdg_conv and rdg_shear. Two of these are used in icepack. The other two are only diagnostic.

The change when moving the call to after the subcycling is that these four parameters are caluclated based on the velocities calulated at ksub=ndte instead of ksub=ndte-1. I am not sure that there is a "correct" time of calculation, however if convergence is assumed this should not differ much.

The benefit is that this is only called once and the if statement from the loop is removed. This should in principle optimize the code, however I think that the mpi communication is the bottleneck.

I can do a qc test and test the difference. If this is acceptable I would move the call to after the subcycling.

**Comment by apcraig** [comment]
I believe this is addressed in #755?  I am closing now, feel free to reopen if needed.
