### ISSUE TITLE
ice_constants

### ISSUE THREAD

**Issue by apcraig** [CICE-Consortium/CICE#74]
Consolidate ice_constants files as needed.  There are only a few differences between cice, cesm, and hadgem.  Do we want to keep them separate, un-parameter them and add init/query methods, or what?

Also, we need to make sure the icepack_constants are set in hadgem and cesm mode during CICE initialization via the init methods.

**Comment by eclare108213** [comment]
The original plan was to move them to namelist so that cesm and hadgem and other groups could set them at runtime.  In fact the plan was to move ALL user-definable constants to namelist, but we might not get that far for the first release..

**Comment by rgrumbine** [comment]
I'll suggest a split of the constants.  

In the first group are some constants that are absolute mathematical constants and cannot be changed -- unit conversion factors, pi, p25 (though I'm concerned about defining numbers this way).  Also some that define the model's working -- field_loc, and field_type.  And a few which are strongly constrained by physics -- gravitational acceleration at the surface of the earth, Stefan-Boltzmann constant, and such.

Second group are moderately well constrained, but some sites might want to change -- density of snow, specific heat of dry air, etc.

Third is variables which have significant room for variation -- ice-ocean drag coefficient, reference salinities, surface roughness, ...

Fourth are approximating things which are not constant (or even linear) -- freezing point of sea water, saturation vapor pressure, ocean albedo, ... -- for my taste, I'd like an option for a full functional representation rather than just a constant.

**Comment by apcraig** [comment]
I have added ability to set the cice constants via an init interface and this is being called in the rasm coupling layer.  I have removed the constants directory and migrated a more flexible constants file into cicecore/shared.  This is currently on fork apcraig, branch rasmA.  It will be PR'ed to the master after further testing.

**Comment by apcraig** [comment]
PR #152

**Comment by eclare108213** [comment]
I think this has been addressed.  If further work is needed for the various modeling centers, we can create a new issue.
