### ISSUE TITLE
OPENACC code in ice_dyn_evp_1d.F90

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/CICE#783]
Apparently the NVIDIA compiler is flagging the OPENACC directives with a syntax error:

NVFORTRAN-S-0034-Syntax error at or near ACCLOOP (/glade/work/jedwards/sandboxes/cesm2_x_alpha/components/cice/src/cicecore/cicedynB/dynamics/ice_dyn_evp_1d.F90: 906)
0 inform, 0 warnings, 1 severes, 0 fatal for evp1d_halo_update

using: Currently Loaded Modules:

ncarenv/1.3 3) nvhpc/22.2 5) netcdf-mpi/4.8.1 7) esmf-8.4.0b08_casper-ncdfio-openmpi-O 9) pio/2.5.9
cmake/3.18.2 4) openmpi/4.1.4 6) pnetcdf/1.12.3 8) ncarcompilers/0.5.0

This is the acc loop starting at line 906. @TillRasmussen , can you have your guys look at this?

**Comment by TillRasmussen** [comment]
ok. I think that I have the reason but I need to talk to our it department tomorrow in order to get acces to a nvidia compiler. I will test it then. If you need a quick fix then try  the following

From line 899. Se bold line below. This should be replaced with 
      **!$acc present(uvel, vvel)**
Thus "&" is removed
#ifdef _OPENACC
      !$acc parallel &
      **!$acc present(uvel, vvel) &**
      !$acc loop
      do iw = 1, NAVEL_len
         if (halo_parent(iw) == 0) cycle
         uvel(iw) = uvel(halo_parent(iw))
         vvel(iw) = vvel(halo_parent(iw))
      end do
      !$acc end parallel
#else

**Comment by dabail10** [comment]
I wondered about the continuation characters. I'll mention it to our software engineers.

**Comment by dabail10** [comment]
Fixed in PR #799 .
