### ISSUE TITLE
Test variable grid spacing for C grid

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#786]

**Comment by JFLemieux73** [comment]
I used the following setup:

./cice.setup --case Bvargrid -g gbox80 -m ppp6 -e intel -p 1x1 -s boxforcee,boxclosed,vargrid,buildincremental

I then changed things in the namelist:
npt=10 (days)
 ndte            = 1200
deltaminEVP     = 2e-9
capping_method  = 'sum'
kridge          = 1
ktransport      = 1
 atm_data_type   = 'uniform_east'
    ocn_data_type   = 'calm'
    bgc_data_type   = 'default'
    fe_data_type    = 'default'
    ice_data_type   = 'uniform'
    ice_data_conc   = 'p5'
    ice_data_dist   = 'uniform'

The runs are 10 days long. I look at the results after 10 days.

**Comment by JFLemieux73** [comment]
Here is hi after 10 days for B-evp:

![Bevp_E_Ap5_hi](https://user-images.githubusercontent.com/31927797/201143529-e919d33a-a13a-4d8e-b2b6-efa98b088790.png)

for C-evp:

![Cevp_E_Ap5_hi](https://user-images.githubusercontent.com/31927797/201143596-2ec75d90-6c67-45a5-8339-4bef3deebfe3.png)

The difference (C-B):

![Cevp_E_Ap5_Bevp_E_Ap5_hi_2005-01-11-00000](https://user-images.githubusercontent.com/31927797/201143683-f6c197fc-cc40-4596-824e-0006f7df05be.png)

Notice that the scales goes from -2 to 2 cm...kind of small differences.

**Comment by JFLemieux73** [comment]
Experiments are repeated with ice_data_conc   = 'p8'. Note that hbar=1 here instead of hbar=2 for ice_data_conc   = 'p5'. 

Here is C-B:

![Cevp_E_Ap8_Bevp_E_Ap8_hi_2005-01-11-00000](https://user-images.githubusercontent.com/31927797/201150797-c88d13fb-d3d2-45ee-8483-905f73cd069f.png)

**Comment by JFLemieux73** [comment]
Hi Elizabeth,

Thermo is off. Can I have thermo "on" with these idealized tests?

**Comment by eclare108213** [comment]
You can always turn it on and see what happens  :)
Looks like you're making good progress with the dynamics by itself.

**Comment by JFLemieux73** [comment]
I also want to verify the pressure fields. Here is for the B grid:
 
![Bevp_E_Ap8_sigP](https://user-images.githubusercontent.com/31927797/201182475-d858b3fc-04bb-4ba6-9f7e-9d171ae4639e.png)

and the C grid:

![Cevp_E_Ap8_sigP](https://user-images.githubusercontent.com/31927797/201182533-3d9d7152-e18a-4e5a-903b-e02f06bfa4f6.png)

**Comment by JFLemieux73** [comment]
Going back to ice_data_conc='p5' and now setting atm_data_type = 'uniform_northeast'

For the B grid:

![Bevp_NE_Ap5_hi](https://user-images.githubusercontent.com/31927797/201184959-e266c2bb-9563-43a7-803c-34db4da1e0ff.png)

and the C grid:

![Cevp_NE_Ap5_hi](https://user-images.githubusercontent.com/31927797/201185001-d572c67d-1a87-4535-b481-bca6a9d4c293.png)

**Comment by JFLemieux73** [comment]
Looking at differences we have (C-B):

![Cevp_NE_Ap5_Bevp_NE_Ap5_hi_2005-01-11-00000](https://user-images.githubusercontent.com/31927797/201185602-a79c26b3-c89e-4e98-a416-7798c65a4ec4.png)

note that the scale goes from -5 to 5 cm.

**Comment by JFLemieux73** [comment]
Do we see a thickening with the C grid (north-east corner)? Is the thickening in gx3-gx1 experiments related to corners?

**Comment by JFLemieux73** [comment]
Now with ice_data_conc = 'p8'. 

B grid:

![Bevp_NE_Ap8_hi](https://user-images.githubusercontent.com/31927797/201187724-12690817-650f-48df-a35b-529f5c39e94c.png)

C grid:

![Cevp_NE_Ap8_hi](https://user-images.githubusercontent.com/31927797/201187781-fe9cc2b0-761c-4a79-ae91-43e961733adc.png)

difference (C-B ):

![Cevp_NE_Ap8_Bevp_NE_Ap8_hi_2005-01-11-00000](https://user-images.githubusercontent.com/31927797/201188030-ab541706-ead7-442d-9ec3-0a0de6b7906b.png)

Again we kind of see a thickening with the C grid. Do we get the same thing with a uniform grid?

**Comment by JFLemieux73** [comment]
Here is sigP for the B grid:

![Bevp_NE_Ap8_sigP](https://user-images.githubusercontent.com/31927797/201188582-dc3b6e5a-9114-4f27-8571-a39d2fabcad1.png)\

and for the C grid:

![Cevp_NE_Ap8_sigP](https://user-images.githubusercontent.com/31927797/201188623-10333373-775c-45c4-b7bf-e96069d1beea.png)

**Comment by JFLemieux73** [comment]
We see something in the northeast corner for both grids. But clearly there is something weird with the C grid corner.

**Comment by eclare108213** [comment]
There is something weird with the C grid corner, but is the B-grid corner right, sigP=0 there?  Maybe that's just because of which value (ne?) is chosen to be written to history?
There are differences in all 4 corners in this test, which is interesting.  Have you tried cranking up the subcycling even further, and/or comparing with VP on the B grid?  It wouldn't be surprising for differences in residual elastic waves to be amplified near corners and also in areas with steep thickness or pressure gradients (like the nw and se corners in this test).

**Comment by JFLemieux73** [comment]
Thanks Elizabeth for your input. I think you are right for sigP=0 for the B-grid. 

I am already using 1200 subcycles. I could try also to reduce the damping time scale for the elastic waves.  

I will also compare against the VP solution and use the upwind for the advection (Dave's idea).

**Comment by JFLemieux73** [comment]
Before doing all these tests I have decided to run these for 30 days instead to make the problem more obvious (ice_data_conc = 'p8'). Here is hi (m) after 30 days for the B grid:

![Bevp_NE_Ap8_hi_2005-02-01-00000](https://user-images.githubusercontent.com/31927797/201929606-57a9fe8c-f51b-44f3-9d6f-b890d87f2eb0.png)

and for the C grid:

![Cevp_NE_Ap8_hi_2005-02-01-00000](https://user-images.githubusercontent.com/31927797/201929673-3ed675d8-7c9b-49d7-a5da-5051c2e53ed0.png)

And the diff (C-B):

![Cevp_NE_Ap8_Bevp_NE_Ap8_hi_2005-02-01-00000](https://user-images.githubusercontent.com/31927797/201929768-56f5f3ab-d595-418d-a794-86165b7f7429.png)

**Comment by JFLemieux73** [comment]
There is an asymmetry in the C grid hi field. We also see the thickening close to the corner when compared to the B grid.

**Comment by JFLemieux73** [comment]
I am taking a step back. I want to see if we get the asymmetry and the thickening with the constant grid. The only differences with the previous runs is that

scale_dxdy     = .false.
dxscale        = 1.d0
dyscale        = 1.d0
 
Instead of:

scale_dxdy     = .true.
dxscale        = 1.02d0
dyscale        = 1.01d0

Interestingly the variable grid changes a lot the results for both B and C grid. Here is the B grid result keeping the same range for the colorbar (0-1.75 m). 

![Bdxcevp_NE_Ap8_hi_2005-02-01-00000](https://user-images.githubusercontent.com/31927797/201939007-ca3f4f7e-b483-4951-b729-10d2c88a046b.png)

**Comment by eclare108213** [comment]
> scale_dxdy = .true.
> dxscale = 1.02d0
> dyscale = 1.01d0

Is the non-symmetry in dxscale and dyscale intentional?  It looks like there is a slight nonsymmetry in the B-grid test, maybe coming from this.  But see also https://github.com/CICE-Consortium/CICE/issues/694 https://github.com/CICE-Consortium/CICE/pull/316

So now there are two mysteries:

1. the solution with variable grid sizing is very different from a constant grid, for either C- or B-grid

Changing the scaling factor by 1 or 2% will change the domain size, which will affect the overall rate of convergence/divergence at the boundaries, but I wouldn't expect it to be big.

We've always suspected that the ice pressure formulation is too grid dependent. Try keeping it constant but allow everything else to use the spatial gradients that are calculated?  Not sure if that will even run with advection on, but you could turn advection off and compare the resulting velocities and stresses.

2. C-grid results are more nonsymmetric with the variable grid than when using B-grid

Is this still true on the constant grid?  If not, then at least we can narrow the search.

**Comment by JFLemieux73** [comment]
I am closing this issue and will start a new one with:

scale_dxdy = .true.
dxscale = 1.01d0
dyscale = 1.01d0

I also want to to get the VP solution and crank up the EVP convergence.
