### ISSUE TITLE
OpenMP Initialization in ice_grid.F90

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/CICE#800]
For some reason, the initialization and printing of the OpenMP threads in ice_grid.F90 causes the code to hang in CESM (cheyenne_intel). When I comment this code out it runs fine. Is there some issue because the decomposition is not yet defined?

**Comment by dabail10** [comment]
I looked at this and the OMP initialization has happened already. So, is it the OMP ordered directive?

**Comment by apcraig** [comment]
All this is doing is diagnosing the thread schedule.  It is not setting anything. It is operating only on master task, so it can't be collective (needed to run on all tasks synchronously).  I don't have a clue why CESM is hanging here.

**Comment by dabail10** [comment]
!$OMP PARALLEL DO ORDERED PRIVATE(iblk) SCHEDULE(runtime)
       do iblk = 1, nblocks
          if (my_task == master_task) then
             !$OMP ORDERED
             if (iblk == 1) then

I have a couple questions about this. Don't we we want the my_task == master_task outside the iblk loop? Then we only do the iblk for the master task. Also, doesn't the OMP ORDERED need to be outside the iblk loop as well? The other dumb question is, if we are only printing for iblk == 1, then why do we need the ordered?

**Comment by dabail10** [comment]
Do ompsk and ompcs have to be private?

**Comment by apcraig** [comment]
The entire block of code is

```
#if defined (_OPENMP)
       !$OMP PARALLEL DO ORDERED PRIVATE(iblk) SCHEDULE(runtime)
       do iblk = 1, nblocks
          if (my_task == master_task) then
             !$OMP ORDERED
             if (iblk == 1) then
                call omp_get_schedule(ompsk,ompcs)
!               write(nu_diag,*) ''
                write(nu_diag,*) subname,' OpenMP runtime thread schedule:'
                write(nu_diag,*) subname,'  omp schedule = ',ompsk,ompcs
             endif
             write(nu_diag,*) subname,' block, thread = ',iblk,OMP_GET_THREAD_NUM()
             call flush_fileunit(nu_diag)
             !$OMP END ORDERED
          endif
       enddo
       !$OMP END PARALLEL DO
#endif

```

And output from a gx3 8x4 case with block size 5x29 and 10 blocks per task is

```
 (init_grid2) OpenMP runtime thread schedule:
 (init_grid2)  omp schedule =            0           0
 (init_grid2) block, thread =            1           0
 (init_grid2) block, thread =            2           1
 (init_grid2) block, thread =            3           2
 (init_grid2) block, thread =            4           3
 (init_grid2) block, thread =            5           0
 (init_grid2) block, thread =            6           1
 (init_grid2) block, thread =            7           2
 (init_grid2) block, thread =            8           3
 (init_grid2) block, thread =            9           0
 (init_grid2) block, thread =           10           1
```

So, we only want/need to diagnose the thread/block schedule/ordering on 1 MPI task.  The other tasks will be the same.  And we are only writing the "omp schedule" for the first block.  The schedule is the same for all blocks and all tasks.  And we want to make sure the blocks are written in order to make the output more readable and reproducible.  Also, think of that "iblk==1" as extra output, it's not the only output.  

We need to thread over blocks to get the threading going.  It's a reasonable question whether the "do iblk" and "if (my_task==master_task)" order could be switched, but it really won't make any different in performance or output.  And we don't really know what happens if we fire up threads on just one MPI task, we don't do that in any other part of the code.

The "OMP ORDERED" is there to synchronize the threads.  If you don't have that, the "block, thread = " output could come out in any order (to some degree).  The "OMP ORDERED" could maybe be placed outside the if or do structures, but in general, you just need to place that directive around the code you want to control the threads.  Again, I'm pretty sure what is implemented is reasonable code.

It's a good questions whether ompsk and ompcs should be private.  They probably should be and we should test that.  But the only problem would be to have incorrect output.  It should not cause the model to hang.  The other thing is that the "OMP ORDERED" command may make it impossible for multiple threads to use ompsk and ompcs at the same time, so making them private may have no affect.

A few questions about CESM.  Have you tested a case with all components running on all cores.  I wonder if the problem is somehow related to component concurrency.  Another thought, when OpenMP is on in CESM, is the ice model running threaded and is the ice model compiled and/or linked with openmp?  I doubt that's playing a role, because it there were a problem here, it would almost certainly show up in other OpenMP regions in CICE.  It's very odd, the above code is pretty benign.  Maybe comment out the "OMP ORDERED" and see if that allows the code to run?

**Comment by dabail10** [comment]
Good questions. I tried removing the OMP ORDERED and that did not work. Trying a case where I move the my_task == master_task.

**Comment by apcraig** [comment]
I would just start commenting out various parts.  See if you can identify which line or call is causing the hang.

**Comment by dabail10** [comment]
Next test is that I put back in the OMP block, but without ordered or schedule. It ran and I got:

 (init_grid2) OpenMP runtime thread schedule:
 (init_grid2) block, thread =            8           1
 (init_grid2)  omp schedule =            0           0
 (init_grid2) block, thread =            1           0
 (init_grid2) block, thread =            2           0
 (init_grid2) block, thread =            9           1
 (init_grid2) block, thread =            3           0
 (init_grid2) block, thread =           10           1
 (init_grid2) block, thread =            4           0
 (init_grid2) block, thread =           11           1
 (init_grid2) block, thread =            5           0
 (init_grid2) block, thread =           12           1
 (init_grid2) block, thread =            6           0
 (init_grid2) block, thread =           13           1
 (init_grid2) block, thread =            7           0
 (init_grid2) block, thread =           14           1

**Comment by dabail10** [comment]
Ok. So, the ORDERED causes this to hang. Not sure why. I might have to enlist Jim Edwards help.

**Comment by dabail10** [comment]
Ok. It was the flush_fileunit. I moved this outside the OMP region.

(init_grid2) OpenMP runtime thread schedule:
 (init_grid2)  omp schedule =            1           0
 (init_grid2) block, thread =            1           0
 (init_grid2) block, thread =            2           0
 (init_grid2) block, thread =            3           0
 (init_grid2) block, thread =            4           0
 (init_grid2) block, thread =            5           0
 (init_grid2) block, thread =            6           0
 (init_grid2) block, thread =            7           0
 (init_grid2) block, thread =            8           1
 (init_grid2) block, thread =            9           1
 (init_grid2) block, thread =           10           1
 (init_grid2) block, thread =           11           1
 (init_grid2) block, thread =           12           1
 (init_grid2) block, thread =           13           1
 (init_grid2) block, thread =           14           1

Dave

**Comment by apcraig** [comment]
Interesting.  I still wonder why it's a problem in CESM and not CICE.  But very happy the solution is relatively straight-forward to work around.  Thanks.

**Comment by dabail10** [comment]
I think it is because nu_diag is negative on the master task and assigned differently in CESM.
