### ISSUE TITLE
Units for some variables in the doc

### ISSUE THREAD

**Issue by JFLemieux73** [CICE-Consortium/CICE#815]
I noticed in the doc (see p. 140 for the pdf) that the units for meltt, meltb, meltl and melts are m (same for congel). Is the doc wrong about these? I would expect something like m/day.

**Comment by eclare108213** [comment]
Hi JF, the units in the code calculations are in m because they are calculated each time step. They are changed to /time by dividing by dt when written out as diagnostics or history.


From: JFLemieux73 ***@***.******@***.***>>
Date: Tuesday, Feb 21, 2023 at 9:06 AM
To: CICE-Consortium/CICE ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: [EXTERNAL] [CICE-Consortium/CICE] Units for some variables in the doc (Issue #815)


I noticed in the doc (see p. 140 for the pdf) that the units for meltt, meltb, meltl and melts are m (same for congel). Is the doc wrong about these? I would expect something like m/day.

**Comment by JFLemieux73** [comment]
Ok! I will close the issue.
