### ISSUE TITLE
version number in documentation, etc

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#85]
Do we want to change the current version number in the CICE code and docs to v6-alpha?  That is how it is referred to in Icepack and my recent presentations.

**Comment by duvivier** [comment]
This has been completed for V6.0.0.alpha release. 

There are only three places where we explicitly need to change the version in the documentation:
1.  /doc/source/conf.py  --> modify "version" and "release" so that the documentation is numbered properly when rendered.

2. /doc/source/intro/about.rst --> explicitly names the model release version.

3. /doc/source/intro/major_updates.rst --> explicitly lists the current version of CICE and major updates since the last release.

I would propose that we have as few places as possible that explicitly reference the current version of the documentation since it will be a living document. In fact, if possible it would be good to combine the two introductory section documents. I just want to minimize how many places this needs to be changed manually with a release so we don't forget to change some.

**Comment by duvivier** [comment]
Addressed with PR #112. Now the only documentation explicitly uses the version in only:
 /doc/source/conf.py 
and
/doc/source/intro/major_updates.rst 

The documentation itself still needs to be updated to be consistent with the current version, but I do not believe the explicit version number is referenced elsewhere. I'm going to close this for now and we will need to update the above two files with the next release.

**Comment by eclare108213** [comment]
version number location is now noted at #91
