### ISSUE TITLE
NCAR derecho compilers

### ISSUE THREAD

**Issue by dabail10** [CICE-Consortium/CICE#967]
A couple things here.

1. We should get rid of derecho_intel and start doing tests with intel-oneapi. Also, intel-classic will be going away, so will need to be removed eventually.

2. All of the cheyenne options need to be removed.

I have a set of PRs for dsnow / dsnown and I will do this.

**Comment by dabail10** [comment]
Also we are getting a ton of warnings as follows with the intel compilers:

ifx: command line warning #10121: overriding '-march=core-avx2' with '-march=core-avx2'

**Comment by apcraig** [comment]
I will be working on the intel-oneapi port.  If you know how to do that, go for it.  Most of it's there, it's just wasn't working a couple months ago due to compiler bugs.

Lets leave the intel-classic there for now.   Also, lets leave the cheyenne stuff for now.  The more examples we have, the better.  We can get rid of cheyenne in a couple years.

The warning message #10121 is irritating, but as far as I'm concerned, that a problem with the compiler, not with our compiler options.  I think explicitly setting -march is better than not.

**Comment by dabail10** [comment]
In terms of the warning, this -march flag is redundant. It is already on by default.

**Comment by eclare108213** [comment]
Can this issue be closed now, since https://github.com/CICE-Consortium/CICE/pull/974 was merged?
